export const CURRENCY_FLAG: Record<string, string> = {
  CNY: 'China',
  BRL: 'Brazil',
  MXN: 'Mexico',
  RUB: 'Russia',
  INR: 'India',
  CAD: 'Canada',
  GBP: 'United Kingdom',
  AUD: 'Australia',
  EGP: 'Egypt',
  USD: 'United States',
  ZAR: 'South Africa',
  SAR: 'Saudi Arabia',
  KRW: 'South Korea',
  JPY: 'Japan',
  EUR: 'European Union',
  BHD: 'Bahrain',
  KWD: 'Kuwait',
  OMR: 'Oman',
  QAR: 'Qatar',
  IQD: 'Iraq',
  AED: 'United Arab Emirates',
  LBP: 'Lebanon',
  JOD: 'Jordan',
  CHF: 'Switzerland',
  DKK: 'Denmark',
  ITL: 'Italy',
  NOK: 'Norway',
  NZD: 'New Zealand',
  SEK: 'Sweden',
};

export enum Currencies {
  CHINESE_YUAN = 'CNY',
  BRAZILIAN_REAL = 'BRL',
  MEXICAN_PESO = 'MXN',
  RUSSIAN_RUBLE = 'RUB',
  INDIAN_RUPEE = 'INR',
  CANADIAN_DOLLAR = 'CAD',
  BRITISH_POUND = 'GBP',
  AUSTRALIAN_DOLLAR = 'AUD',
  EGYPTIAN_POUND = 'EGP',
  US_DOLLAR = 'USD',
  SOUTH_AFRICAN_RAND = 'ZAR',
  SAUDI_RIYAL = 'SAR',
  SOUTH_KOREAN_WON = 'KRW',
  JAPANESE_YEN = 'JPY',
  EURO = 'EUR',
  BAHRAINI_DINAR = 'BHD',
  KUWAITI_DINAR = 'KWD',
  OMANI_RIAL = 'OMR',
  QATARI_RIYAL = 'QAR',
  IRAQI_DINAR = 'IQD',
  UAE_DIRHAM = 'AED',
  LEBANESE_POUND = 'LBP',
  JORDANIAN_DINAR = 'JOD',
  SWISS_FRANC = 'CHF',
  DANISH_KRONE = 'DKK',
  ITALIAN_LIRA = 'ITL',
  NORWEGIAN_KRONE = 'NOK',
  NEW_ZEALAND_DOLLAR = 'NZD',
  SWEDISH_KRONA = 'SEK',
}
