import { Injectable } from '@nestjs/common';

@Injectable()
export class ProductsService {
  getCdList() {
    return {
      successful: true,
      message: 'Fetched Successfully',
      data: [
        {
          cdTdId: 'USD-600-12M-36M',
          title: 'Fixed Income USD Certificate',
          interestRate: '10',
          frequency: 'Annual',
          interestType: 'FIXED',
          minimumDeposit: '600 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '36M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-600-12M-36M',
          title: 'Fixed Income USD Certificate',
          interestRate: '7',
          frequency: 'Annual',
          interestType: 'FIXED',
          minimumDeposit: '600 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '36M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-1000-12M-36M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.30',
          frequency: 'Annual',
          interestType: 'FIXED',
          minimumDeposit: '1000 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '36M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-5000-12M-36M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.30',
          frequency: 'Annual',
          interestType: 'FIXED',
          minimumDeposit: '5000 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '36M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-10000-12M-36M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.30',
          frequency: 'Annual',
          interestType: 'FIXED',
          minimumDeposit: '10000 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '36M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-100000-12M-36M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.30',
          frequency: 'Annual',
          interestType: 'FIXED',
          minimumDeposit: '100000 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '36M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-100-3M-36M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.20',
          frequency: 'Quarterly',
          interestType: 'FIXED',
          minimumDeposit: '100 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '36M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-500-3M-36M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.20',
          frequency: 'Quarterly',
          interestType: 'FIXED',
          minimumDeposit: '500 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '36M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-1000-3M-36M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.20',
          frequency: 'Quarterly',
          interestType: 'FIXED',
          minimumDeposit: '1000 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '36M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-100-12M-60M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.15',
          frequency: 'Annual',
          interestType: 'FIXED',
          minimumDeposit: '100 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '60M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-500-12M-60M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.15',
          frequency: 'Annual',
          interestType: 'FIXED',
          minimumDeposit: '500 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '60M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-1000-12M-60M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.15',
          frequency: 'Annual',
          interestType: 'FIXED',
          minimumDeposit: '1000 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '60M',
          tdType: null,
          tdRef: null,
          new: true,
        },
        {
          cdTdId: 'USD-1000000-6M-60M',
          title: 'Fixed Income USD Certificate',
          interestRate: '5.10',
          frequency: 'Semi Annual',
          interestType: 'FIXED',
          minimumDeposit: '1000000 USD',
          categoryId: '21025',
          currency: 'USD',
          duration: '60M',
          tdType: null,
          tdRef: null,
          new: true,
        },
      ],
    };
  }

  getTDList() {
    return {
      successful: true,
      message: 'Fetched Successfully',
      data: [
        {
          title: 'Time Deposit -Floating Interest',
          interestRate: '13.755 - 18.255 : 13.755',
          frequency: '12M',
          interestType: 'EGP',
          minimumDeposit: '2000',
          categoryId: '21012',
          currency: 'EGP',
          duration: null,
          tdType: 'FLOATING',
          tdRef: '21012-12M',
          new: true,
        },
        {
          title: 'Time Deposit -Floating Interest',
          interestRate: '15.755 - 19.255 : 15.755',
          frequency: '12M',
          interestType: 'EGP',
          minimumDeposit: '100000',
          categoryId: '21012',
          currency: 'EGP',
          duration: null,
          tdType: 'FLOATING',
          tdRef: '21012-12M',
          new: true,
        },
        {
          title: 'Time Deposit -Floating Interest',
          interestRate: '16.755 - 19.755 : 16.755',
          frequency: '1M',
          interestType: 'EGP',
          minimumDeposit: '2000',
          categoryId: '21012',
          currency: 'EGP',
          duration: null,
          tdType: 'FLOATING',
          tdRef: '21012-1M',
          new: true,
        },
        {
          title: 'Time Deposit -Floating Interest',
          interestRate: '11.755 - 17.255 : 11.755',
          frequency: '1W',
          interestType: 'EGP',
          minimumDeposit: '2000',
          categoryId: '21012',
          currency: 'EGP',
          duration: null,
          tdType: 'FLOATING',
          tdRef: '21012-1W',
          new: true,
        },
        {
          title: 'Time Deposit -Floating Interest',
          interestRate: '16.755 - 19.755 : 16.755',
          frequency: '2M',
          interestType: 'EGP',
          minimumDeposit: '2000',
          categoryId: '21012',
          currency: 'EGP',
          duration: null,
          tdType: 'FLOATING',
          tdRef: '21012-2M',
          new: true,
        },
        {
          title: 'Time Deposit -Floating Interest',
          interestRate: '12.755 - 17.755 : 12.755',
          frequency: '9M',
          interestType: 'EGP',
          minimumDeposit: '2000',
          categoryId: '21012',
          currency: 'EGP',
          duration: null,
          tdType: 'FLOATING',
          tdRef: '21012-9M',
          new: true,
        },
        {
          title: 'Time Deposit -Floating Interest',
          interestRate: '14.755 - 18.755 : 14.755',
          frequency: '9M',
          interestType: 'EGP',
          minimumDeposit: '100000',
          categoryId: '21012',
          currency: 'EGP',
          duration: null,
          tdType: 'FLOATING',
          tdRef: '21012-9M',
          new: true,
        },
        {
          title: 'Time Deposit -Floating Interest',
          interestRate: '16.755 - 19.755 : 16.755',
          frequency: '9M',
          interestType: 'EGP',
          minimumDeposit: '500000',
          categoryId: '21012',
          currency: 'EGP',
          duration: null,
          tdType: 'FLOATING',
          tdRef: '21012-9M',
          new: true,
        },
        {
          title: 'Time Deposit -Floating Interest',
          interestRate: '17.755 - 20.255 : 17.755',
          frequency: '9M',
          interestType: 'EGP',
          minimumDeposit: '1000000',
          categoryId: '21012',
          currency: 'EGP',
          duration: null,
          tdType: 'FLOATING',
          tdRef: '21012-9M',
          new: true,
        },
        {
          title: 'Time Deposit - One Week',
          interestRate: '10.00',
          frequency: '1W',
          interestType: 'EGP',
          minimumDeposit: '2000',
          categoryId: '21001',
          currency: 'EGP',
          duration: null,
          tdType: 'FIXED',
          tdRef: null,
          new: true,
        },
        {
          title: 'Time Deposit - One Week',
          interestRate: '3.03',
          frequency: '1W',
          interestType: 'USD',
          minimumDeposit: '100',
          categoryId: '21001',
          currency: 'USD',
          duration: null,
          tdType: 'FIXED',
          tdRef: null,
          new: true,
        },
        {
          title: 'Time Deposit - One Month',
          interestRate: '13.50',
          frequency: '1M',
          interestType: 'EGP',
          minimumDeposit: '10000',
          categoryId: '21003',
          currency: 'EGP',
          duration: null,
          tdType: 'FIXED',
          tdRef: null,
          new: true,
        },
        {
          title: 'Time Deposit - One Month',
          interestRate: '3.02719',
          frequency: '1M',
          interestType: 'USD',
          minimumDeposit: '100',
          categoryId: '21003',
          currency: 'USD',
          duration: null,
          tdType: 'FIXED',
          tdRef: null,
          new: true,
        },
        {
          title: 'Time Deposit - Three Months',
          interestRate: '14.00',
          frequency: '3M',
          interestType: 'EGP',
          minimumDeposit: '2000',
          categoryId: '21005',
          currency: 'EGP',
          duration: null,
          tdType: 'FIXED',
          tdRef: null,
          new: true,
        },
        {
          title: 'Time Deposit - Three Months',
          interestRate: '2.50267',
          frequency: '3M',
          interestType: 'USD',
          minimumDeposit: '100',
          categoryId: '21005',
          currency: 'USD',
          duration: null,
          tdType: 'FIXED',
          tdRef: null,
          new: true,
        },
        {
          title: 'Time Deposit - One Year',
          interestRate: '15.00',
          frequency: '1Y',
          interestType: 'EGP',
          minimumDeposit: '2000',
          categoryId: '21007',
          currency: 'EGP',
          duration: null,
          tdType: 'FIXED',
          tdRef: null,
          new: true,
        },
        {
          title: 'Time Deposit - One Year',
          interestRate: '1.76494',
          frequency: '1Y',
          interestType: 'USD',
          minimumDeposit: '100',
          categoryId: '21007',
          currency: 'USD',
          duration: null,
          tdType: 'FIXED',
          tdRef: null,
          new: true,
        },
      ],
    };
  }

  getAllAccounts() {
    return {
      status: 'Success',
      message: 'Fetched successfully',
      data: [
        {
          accountListResponse: {
            accountType: 'CURRENT.ACCOUNT',
            accountTitle: 'Golden Current',
            accountDescription: 'Golden Current Account',
            categoryId: '1024',
            productId: '1024-EGP-Interest-NONE',
            interestType: 'Interest',
            frequency: 'DAILY',
            minimumDeposit: '99999.99',
            minForInterest: '99999.99',
            currency: 'EGP',
            checkBookAvailable: true,
          },
          interestRateResponses: [
            {
              from: '99999.99',
              to: '499999.99',
              interestRate: '10',
            },
            {
              from: '99999.99',
              to: '999999.99',
              interestRate: '12',
            },
            {
              from: '99999.99',
              to: '4999999.99',
              interestRate: '13',
            },
            {
              from: '99999.99',
              to: '9999999.99',
              interestRate: '13.5',
            },
            {
              from: '99999.99',
              to: '19999999.99',
              interestRate: '14',
            },
            {
              from: '99999.99',
              to: '49999999.99',
              interestRate: '14.5',
            },
            {
              from: '99999.99',
              to: '9223372036854775807',
              interestRate: '15',
            },
          ],
        },
        {
          accountListResponse: {
            accountType: 'CURRENT.ACCOUNT',
            accountTitle: 'Current Account',
            accountDescription: 'Current Account',
            categoryId: '1001',
            productId: '1001-null-Non-Interest-NONE',
            interestType: 'Non-Interest',
            frequency: 'DAILY',
            checkBookAvailable: true,
          },
        },
      ],
    };
  }

  getCd() {
    return {
      status: 'Success',
      message: 'Fetched successfully',
      data: {
        cdTdId: 'USD-500-12M-36M',
        title: 'Fixed Income USD Certificate',
        interestRate: '5.30',
        frequency: 'Annual',
        interestType: 'FIXED',
        minimumDeposit: '500 USD',
        categoryId: '21025',
        currency: 'USD',
        duration: '36M',
        tdType: null,
        tdRef: null,
        maturityAction: 'Redeem',
        new: true,
      },
    };
  }

  getTd() {
    return {
      successful: true,
      message: 'Fetched Successfully',
      data: {
        cdTdId: 'USD-600-12M-36M',
        title: 'Fixed Income USD Certificate',
        interestRate: '10',
        frequency: 'Annual',
        interestType: 'FIXED',
        minimumDeposit: '600 USD',
        categoryId: '21025',
        currency: 'USD',
        duration: '36M',
        tdType: null,
        tdRef: null,
        new: true,
      },
    };
  }

  getAccount() {
    return {
      status: 'Success',
      message: 'Fetched successfully',
      data: {
        accountListResponse: {
          accountType: 'CURRENT.ACCOUNT',
          accountTitle: 'Golden Current',
          accountDescription: 'Golden Current Account',
          categoryId: '1024',
          productId: '1024-EGP-Interest-NONE',
          interestType: 'Interest',
          frequency: 'DAILY',
          minimumDeposit: '5000',
          minForInterest: '99999.99',
          currency: 'EGP',
          checkBookAvailable: true,
        },
        interestRateResponses: [
          {
            from: '99999.99',
            to: '499999.99',
            interestRate: '10',
          },
          {
            from: '99999.99',
            to: '999999.99',
            interestRate: '12',
          },
          {
            from: '99999.99',
            to: '4999999.99',
            interestRate: '13',
          },
          {
            from: '99999.99',
            to: '9999999.99',
            interestRate: '13.5',
          },
          {
            from: '99999.99',
            to: '19999999.99',
            interestRate: '14',
          },
          {
            from: '99999.99',
            to: '49999999.99',
            interestRate: '14.5',
          },
          {
            from: '99999.99',
            to: '9223372036854775807',
            interestRate: '15',
          },
        ],
      },
      // {
      //     "accountListResponse": {
      //         "accountType": "CURRENT.ACCOUNT",
      //         "accountTitle": "Current Account",
      //         "accountDescription": "Current Account",
      //         "categoryId": "1001",
      //         "productId": "1001-EGP-Non-Interest-NONE",
      //         "interestType": "Non-Interest",
      //         "minimumDeposit": "5000",
      //         "currency": "EGP",
      //         "checkBookAvailable": true
      //     }
      // }
    };
  }

  details() {
    return {
      status: 'Success',
      message: 'Product request detail fetched successfully',
      data: {
        productDetail: {
          cdTdId: 'EGP-2000-12M',
          productTitle: 'USD 3-Year CD',
          requestType: 'CD',
          requestId: 'DB9E230D2031423A88C3088AF0C194CB',
          requestTypeDisplay: 'Open New CD',
          status: 'APPROVED',
          requiredApproval: 3,
          approved: 1,
          rejected: 1,
          debitAccount: '1231234432',
          debitAccountHolderNickName: 'ABC',
          creditPrincipleAccount: '23423423',
          creditAccountHolderNickName: 'XYZ',
          amount: '10000',
          currency: 'EGP',
          interestRate: '15',
          minimumDepositAmount: '10000',
          minimumDepositCurrency: 'EGP',
          frequency: '1M',
          interestType: 'FIXED',
          actionAtMaturity: 'Redeem',
          createdDate: '2025-08-04T18:33:11.573268',
          updatedDate: '2025-08-04T18:33:12.547683',
          updatedBy: 'dinesh_super_user',
          createdBy: 'dinesh_super_user',
        },
        approvalRejection: [
          {
            status: 'APPROVED',
            role: 'CHECKER_LEVEL_1',
            approverName: 'Mostafa',
            note: 'rejection or approval note',
            createdAt: '2025-08-10T21:08:08.134039',
          },
        ],
        users: {
          CHECKER_LEVEL_2: [
            {
              name: 'ahmed',
              id: 'uuid',
            },
            {
              name: 'ahmed',
              id: 'uuid',
            },
          ],
          CHECKER_LEVEL_3: [
            {
              name: 'ahmed',
              id: 'uuid',
            },
            {
              name: 'ahmed',
              id: 'uuid',
            },
          ],
        },
      },
    };
  }
}
